// <auto-generated />
using System;
using HomeMaids.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeMaids.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeMaids.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HomeMaids.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("MonthlyPlan")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyVisits")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingNumber")
                        .IsUnique();

                    b.HasIndex("CouponId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkerId", "BookingDate");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HomeMaids.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WELCOME20",
                            Description = "خصم 20% للعملاء الجدد (حد أقصى 5 ر.ع.)",
                            DiscountType = 0,
                            DiscountValue = 20m,
                            IsActive = true,
                            MaxDiscountAmount = 5m,
                            MinOrderAmount = 5m,
                            UsageLimit = 1000,
                            UsedCount = 0,
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "SAVE2",
                            Description = "خصم 2 ر.ع. على الحجوزات أكثر من 8 ر.ع.",
                            DiscountType = 1,
                            DiscountValue = 2m,
                            IsActive = true,
                            MinOrderAmount = 8m,
                            UsageLimit = 500,
                            UsedCount = 0,
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HomeMaids.Models.EmailConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppPassword")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("bit");

                    b.Property<string>("FromEmail")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<bool>("ShowOtpInDev")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("EmailConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppPassword = "",
                            EnableSsl = true,
                            FromEmail = "althiqaglobalom@gmail.com",
                            FromName = "الثقة العالمية لخدمات التنظيف",
                            Host = "smtp.gmail.com",
                            IsActive = true,
                            Port = 587,
                            ShowOtpInDev = true,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "althiqaglobalom@gmail.com"
                        });
                });

            modelBuilder.Entity("HomeMaids.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("UserId", "WorkerId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("HomeMaids.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HomeMaids.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خصم 20% على أول حجز للعملاء الجدد",
                            DiscountType = 0,
                            DiscountValue = 20m,
                            ImageUrl = "/images/offers/welcome.jpg",
                            IsActive = true,
                            Title = "خصم الترحيب 20%",
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خصم خاص بمناسبة شهر رمضان المبارك",
                            DiscountType = 0,
                            DiscountValue = 15m,
                            ImageUrl = "/images/offers/ramadan.jpg",
                            IsActive = true,
                            Title = "عرض رمضان",
                            ValidFrom = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HomeMaids.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CardHolderName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayResponse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("TransactionRef")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HomeMaids.Models.PaymentGatewayConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CancelUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CheckoutBaseUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLive")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PublishableKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SuccessUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("PaymentGatewayConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiBaseUrl = "https://checkout.thawani.om/api/v1",
                            CancelUrl = "/Payments/ThawaniCancel",
                            CheckoutBaseUrl = "https://checkout.thawani.om/pay/",
                            DisplayName = "Thawani Pay",
                            IsActive = true,
                            IsLive = true,
                            Provider = "Thawani",
                            PublishableKey = "g29bBIGL8U8PsSH0iFaAGOXwcb1MfU",
                            SecretKey = "GFi9XiaHOrKzSdkbbYXnNMQy8WSsLA",
                            SuccessUrl = "/Payments/ThawaniSuccess",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HomeMaids.Models.PhoneOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Phone", "CreatedAt");

                    b.ToTable("PhoneOtps");
                });

            modelBuilder.Entity("HomeMaids.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HomeMaids.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 3.000m,
                            Description = "تنظيف منزلي شامل لكل الغرف",
                            IconClass = "bi-house-heart",
                            IsActive = true,
                            Name = "تنظيف عام"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 3.000m,
                            Description = "تنظيف داخلي تفصيلي للأرضيات والمطبخ والحمامات",
                            IconClass = "bi-house-door",
                            IsActive = true,
                            Name = "تنظيف داخلي"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 3.000m,
                            Description = "خدمات غسيل وكي مع التوصيل",
                            IconClass = "bi-tsunami",
                            IsActive = true,
                            Name = "غسيل وكي ملابس"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 3.500m,
                            Description = "تنظيف الواجهات والأسطح والحديقة",
                            IconClass = "bi-tree",
                            IsActive = true,
                            Name = "تنظيف خارجي"
                        });
                });

            modelBuilder.Entity("HomeMaids.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("HomeMaids.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("HomeMaids.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Availability");

                    b.HasIndex("FullName");

                    b.HasIndex("ServiceId");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 32,
                            Availability = 0,
                            AverageRating = 4.8m,
                            Bio = "خبرة طويلة في تنظيف المنازل والاهتمام بالتفاصيل.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "فاطمة عبدالله",
                            HourlyRate = 3.000m,
                            IsActive = true,
                            Languages = "العربية، الإنجليزية",
                            Nationality = "فلبينية",
                            PhotoUrl = "/images/workers/w1.jpg",
                            ServiceId = 1,
                            TotalBookings = 124,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 2,
                            Age = 29,
                            Availability = 0,
                            AverageRating = 4.7m,
                            Bio = "متخصصة في التنظيف الداخلي وغسيل الستائر.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "ماريا سانتوس",
                            HourlyRate = 3.000m,
                            IsActive = true,
                            Languages = "الإنجليزية",
                            Nationality = "فلبينية",
                            PhotoUrl = "/images/workers/w2.jpg",
                            ServiceId = 2,
                            TotalBookings = 89,
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 3,
                            Age = 34,
                            Availability = 0,
                            AverageRating = 4.9m,
                            Bio = "خبرة في تنظيف الواجهات والأسطح.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "أمينة كانتي",
                            HourlyRate = 3.500m,
                            IsActive = true,
                            Languages = "الإنجليزية، السواحلية",
                            Nationality = "كينية",
                            PhotoUrl = "/images/workers/w3.jpg",
                            ServiceId = 4,
                            TotalBookings = 156,
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 4,
                            Age = 27,
                            Availability = 1,
                            AverageRating = 4.6m,
                            Bio = "متخصصة في غسيل وكي الملابس.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "ساندرا ميندوزا",
                            HourlyRate = 3.000m,
                            IsActive = true,
                            Languages = "الإندونيسية، الإنجليزية",
                            Nationality = "إندونيسية",
                            PhotoUrl = "/images/workers/w4.jpg",
                            ServiceId = 3,
                            TotalBookings = 67,
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 5,
                            Age = 31,
                            Availability = 0,
                            AverageRating = 4.85m,
                            Bio = "تنظيف عام واهتمام بالتفاصيل.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "ليلى نصور",
                            HourlyRate = 3.000m,
                            IsActive = true,
                            Languages = "العربية، الأمهرية",
                            Nationality = "إثيوبية",
                            PhotoUrl = "/images/workers/w5.jpg",
                            ServiceId = 1,
                            TotalBookings = 98,
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 6,
                            Age = 35,
                            Availability = 0,
                            AverageRating = 4.95m,
                            Bio = "خبرة عشر سنوات في خدمة المنازل.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "كلارا أوغوستو",
                            HourlyRate = 3.000m,
                            IsActive = true,
                            Languages = "الإنجليزية، التاغالوغ",
                            Nationality = "فلبينية",
                            PhotoUrl = "/images/workers/w6.jpg",
                            ServiceId = 1,
                            TotalBookings = 210,
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("HomeMaids.Models.WorkerSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkerSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 1
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 24,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 25,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 26,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 27,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 28,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 29,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 30,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 31,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 32,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 33,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 34,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 35,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 36,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 6
                        },
                        new
                        {
                            Id = 37,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 6
                        },
                        new
                        {
                            Id = 38,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 6
                        },
                        new
                        {
                            Id = 39,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 6
                        },
                        new
                        {
                            Id = 40,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 6
                        },
                        new
                        {
                            Id = 41,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 6
                        },
                        new
                        {
                            Id = 42,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkerId = 6
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HomeMaids.Models.Booking", b =>
                {
                    b.HasOne("HomeMaids.Models.Coupon", "Coupon")
                        .WithMany("Bookings")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HomeMaids.Models.ApplicationUser", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeMaids.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HomeMaids.Models.Worker", "Worker")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("HomeMaids.Models.Favorite", b =>
                {
                    b.HasOne("HomeMaids.Models.ApplicationUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeMaids.Models.Worker", "Worker")
                        .WithMany("Favorites")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("HomeMaids.Models.Notification", b =>
                {
                    b.HasOne("HomeMaids.Models.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeMaids.Models.Payment", b =>
                {
                    b.HasOne("HomeMaids.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("HomeMaids.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HomeMaids.Models.Review", b =>
                {
                    b.HasOne("HomeMaids.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("HomeMaids.Models.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeMaids.Models.ApplicationUser", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeMaids.Models.Worker", "Worker")
                        .WithMany("Reviews")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("HomeMaids.Models.UserAddress", b =>
                {
                    b.HasOne("HomeMaids.Models.ApplicationUser", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeMaids.Models.Worker", b =>
                {
                    b.HasOne("HomeMaids.Models.Service", "Service")
                        .WithMany("Workers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HomeMaids.Models.WorkerSchedule", b =>
                {
                    b.HasOne("HomeMaids.Models.Worker", "Worker")
                        .WithMany("Schedules")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HomeMaids.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HomeMaids.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeMaids.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HomeMaids.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeMaids.Models.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("HomeMaids.Models.Booking", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("HomeMaids.Models.Coupon", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HomeMaids.Models.Service", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("HomeMaids.Models.Worker", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
